const Characters = {
  Grunewald: {
    name: "Louis Grunewald",
    occupation: "Professor",
    sex: "M",
    age: 53,
    nationality: "USA",
    residence: "Arkham",
    stats: {
      str: 14,
      dex: 12,
      int: 14,
      idea: 70,
      con: 10,
      app: 11,
      pow: 11,
      luck: 55,
      siz: 9,
      san: 55,
      edu: 19,
      know: 95,
      schools: "U. Chicago",
      degrees: "M.A., Ph. D.",
      damageModifier: 0,
      magicPoints: 11,
      hitPoints: 10,
      sanityPoints: 55
    },
    skills: {
      accounting: 10,
      anthropology: 0,
      archaeology: 0,
      astronomy: 0,
      bargain: 5,
      botany: 0,
      camouflage: 25,
      chemistry: 0,
      climb: 40,
      creditRating: 15,
      cryptography: 0,
      cthulhuMythos: 0,
      debate: 10,
      diagnoseDisease: 5,
      dodge: 24,
      driveAutomobile: 20,
      egyptology: 0,
      fastTalk: 5,
      firstAid: 30,
      geology: 0,
      hide: 10,
      antiquity: 20,
      jump: 25,
      law: 5,
      libraryUse: 25,
      linguist: 0,
      listen: 25,
      makeMaps: 10,
      mechanicalRepair: 20,
      navigate: 0,
      occult: 5,
      operateHeavyMachinery: 0,
      oratory: 5,
      pharmacy: 0,
      photography: 10,
      pickPocket: 5,
      pilotAircraft: 0,
      psychoanalysis: 0,
      psychology: 5,
      languageEnglish: 95,
      languageGerman: 0,
      languageLatin: 0,
      languageNordic: 0,
      languageEgHieroglyph: 0,
      ride: 5,
      sneak: 10,
      speak: 0,
      spotHidden: 25,
      survival: 5,
      swim: 25,
      throwAction: 25,
      track: 10,
      treatDisease: 5,
      treatPoison: 5
    },
    bonusSkills: {
      accounting: false,
      anthropology: false,
      archaeology: true,
      astronomy: true,
      bargain: false,
      botany: false,
      camouflage: false,
      chemistry: false,
      climb: false,
      creditRating: false,
      cryptography: false,
      cthulhuMythos: false,
      debate: false,
      diagnoseDisease: false,
      dodge: false,
      driveAutomobile: false,
      egyptology: false,
      fastTalk: false,
      firstAid: false,
      geology: false,
      hide: false,
      antiquity: true,
      jump: false,
      law: false,
      libraryUse: true,
      linguist: false,
      listen: false,
      makeMaps: false,
      mechanicalRepair: false,
      navigate: false,
      occult: true,
      operateHeavyMachinery: false,
      oratory: true,
      pharmacy: false,
      photography: false,
      pickPocket: false,
      pilotAircraft: false,
      psychoanalysis: false,
      psychology: false,
      languageEnglish: false,
      languageGerman: true,
      languageLatin: true,
      languageNordic: true,
      languageEgHieroglyph: true,
      ride: false,
      sneak: false,
      speak: false,
      spotHidden: false,
      survival: false,
      swim: false,
      throwAction: false,
      track: false,
      treatDisease: false,
      treatPoison: false
    },
    weapons: {
      fist: () => rollDice(1, 3),
      kick: () => rollDice(1, 6),
      headButt: () => rollDice(1, 4),
      grapple: 0,
      epee: () => rollDice(1, 6) + 1,
      revolver45: () => rollDice(1, 10) + 2,
      gauge12: () => rollDice(2, 6)
    },
    miscellaneous: [
      {
        relationship: "Friends with",
        name: "Ernest Holt"
      },
      {
        relationship: "Instructed",
        name: "Nora McShane"
      },
      {
        relationship: "Instructed",
        name: "Devon Wilson"
      },
    ],
    pointAllotment: {
      skillPoints: 355,
      bonusSkillPoints: 150
    },
    money: 2200,
  },
  Holt: {
    name: "Ernest Holt",
    occupation: "Industrialist",
    sex: "M",
    age: 62,
    nationality: "USA",
    residence: "New York City",
    stats: {
      str: 9,
      dex: 6,
      int: 16,
      idea: 80,
      con: 7,
      app: 12,
      pow: 10,
      luck: 50,
      siz: 16,
      san: 50,
      edu: 11,
      know: 55,
      schools: "Rensselaer",
      degrees: "B.S.",
      damageModifier: () => rollDice(1, 4),
      magicPoints: 10,
      hitPoints: 12,
      sanityPoints: 50
    },
    skills: {
      accounting: 10,
      anthropology: 0,
      archaeology: 0,
      astronomy: 0,
      bargain: 5,
      botany: 0,
      camouflage: 25,
      chemistry: 0,
      climb: 40,
      creditRating: 15,
      cryptography: 0,
      cthulhuMythos: 0,
      debate: 10,
      diagnoseDisease: 5,
      dodge: 12,
      driveAutomobile: 20,
      egyptology: 0,
      fastTalk: 5,
      firstAid: 30,
      geology: 0,
      hide: 10,
      antiquity: 20,
      jump: 25,
      law: 5,
      libraryUse: 25,
      linguist: 0,
      listen: 25,
      makeMaps: 10,
      mechanicalRepair: 20,
      navigate: 0,
      occult: 5,
      operateHeavyMachinery: 0,
      oratory: 5,
      pharmacy: 0,
      photography: 10,
      pickPocket: 5,
      pilotAircraft: 0,
      psychoanalysis: 0,
      psychology: 5,
      languageEnglish: 55,
      languageGerman: 0,
      languageLatin: 0,
      languageNordic: 0,
      languageEgHieroglyph: 0,
      ride: 5,
      sneak: 10,
      speak: 0,
      spotHidden: 25,
      survival: 5,
      swim: 25,
      throwAction: 25,
      track: 10,
      treatDisease: 5,
      treatPoison: 5
    },
    bonusSkills: {
      accounting: true,
      anthropology: false,
      archaeology: false,
      astronomy: false,
      bargain: false,
      botany: false,
      camouflage: false,
      chemistry: false,
      climb: false,
      creditRating: true,
      cryptography: true,
      cthulhuMythos: false,
      debate: false,
      diagnoseDisease: false,
      dodge: false,
      driveAutomobile: false,
      egyptology: true,
      fastTalk: false,
      firstAid: false,
      geology: false,
      hide: false,
      antiquity: false,
      jump: false,
      law: true,
      libraryUse: false,
      linguist: false,
      listen: false,
      makeMaps: false,
      mechanicalRepair: false,
      navigate: false,
      occult: false,
      operateHeavyMachinery: false,
      oratory: false,
      pharmacy: false,
      photography: true,
      pickPocket: false,
      pilotAircraft: false,
      psychoanalysis: true,
      psychology: false,
      languageEnglish: true,
      languageGerman: false,
      languageLatin: false,
      languageNordic: false,
      languageEgHieroglyph: false,
      ride: false,
      sneak: true,
      speak: false,
      spotHidden: false,
      survival: true,
      swim: false,
      throwAction: false,
      track: true,
      treatDisease: false,
      treatPoison: false
    },
    weapons: {
      fist: () => rollDice(1, 3) + rollDice(1, 4),
      kick: () => rollDice(1, 6) + rollDice(1, 4),
      headButt: () => rollDice(2, 4),
      grapple: 0,
      club: () => rollDice(1, 6) + rollDice(1, 4),
      revolver45: () => rollDice(1, 10) + 2,
      gauge12: () => rollDice(2, 6)
    },
    miscellaneous: [
      {
        relationship: "Friends with",
        name: "Lousis Grunewald"
      },
      {
        relationship: "Friends with",
        name: "Nora McShane"
      },
      {
        relationship: "Commanded",
        name: "Devon Wilson"
      },
    ],
    pointAllotment: {
      skillPoints: 255,
      bonusSkillPoints: 150
    },
    money: 35000,
  },
  McShane: {
    name: "Nora McShane",
    occupation: "Reporter",
    sex: "F",
    age: 23,
    nationality: "USA",
    residence: "New York City",
    stats: {
      str: 11,
      dex: 11,
      int: 13,
      idea: 65,
      con: 12,
      app: 13,
      pow: 11,
      luck: 55,
      siz: 9,
      san: 55,
      edu: 14,
      know: 70,
      schools: "Miskatonic",
      degrees: "None",
      damageModifier: 0,
      magicPoints: 11,
      hitPoints: 12,
      sanityPoints: 55
    },
    skills: {
      accounting: 10,
      anthropology: 0,
      archaeology: 0,
      astronomy: 0,
      bargain: 5,
      botany: 0,
      camouflage: 25,
      chemistry: 0,
      climb: 40,
      creditRating: 15,
      cryptography: 0,
      cthulhuMythos: 0,
      debate: 10,
      diagnoseDisease: 5,
      dodge: 22,
      driveAutomobile: 20,
      egyptology: 0,
      fastTalk: 5,
      firstAid: 30,
      geology: 0,
      hide: 10,
      antiquity: 20,
      jump: 25,
      law: 5,
      libraryUse: 25,
      linguist: 0,
      listen: 25,
      makeMaps: 10,
      mechanicalRepair: 20,
      navigate: 0,
      occult: 5,
      operateHeavyMachinery: 0,
      oratory: 5,
      pharmacy: 0,
      photography: 10,
      pickPocket: 5,
      pilotAircraft: 0,
      psychoanalysis: 0,
      psychology: 5,
      languageEnglish: 70,
      languageGerman: 0,
      languageLatin: 0,
      languageNordic: 0,
      languageEgHieroglyph: 0,
      ride: 5,
      sneak: 10,
      speak: 0,
      spotHidden: 25,
      survival: 5,
      swim: 25,
      throwAction: 25,
      track: 10,
      treatDisease: 5,
      treatPoison: 5
    },
    bonusSkills: {
      accounting: false,
      anthropology: false,
      archaeology: false,
      astronomy: false,
      bargain: false,
      botany: false,
      camouflage: false,
      chemistry: false,
      climb: false,
      creditRating: false,
      cryptography: false,
      cthulhuMythos: false,
      debate: false,
      diagnoseDisease: false,
      dodge: false,
      driveAutomobile: false,
      egyptology: false,
      fastTalk: false,
      firstAid: false,
      geology: false,
      hide: false,
      antiquity: false,
      jump: false,
      law: true,
      libraryUse: false,
      linguist: false,
      listen: false,
      makeMaps: false,
      mechanicalRepair: false,
      navigate: false,
      occult: true,
      operateHeavyMachinery: false,
      oratory: true,
      pharmacy: false,
      photography: false,
      pickPocket: false,
      pilotAircraft: false,
      psychoanalysis: false,
      psychology: false,
      languageEnglish: false,
      languageGerman: true,
      languageLatin: true,
      languageNordic: true,
      languageEgHieroglyph: true,
      ride: false,
      sneak: false,
      speak: false,
      spotHidden: false,
      survival: false,
      swim: false,
      throwAction: false,
      track: false,
      treatDisease: false,
      treatPoison: false
    },
    weapons: {
      fist: () => rollDice(1, 3),
      kick: () => rollDice(1, 6),
      headButt: () => rollDice(1, 4),
      grapple: 0,
      club: () => rollDice(1, 6),
      revolver45: () => rollDice(1, 10) + 2,
      gauge12: () => rollDice(2, 6)
    },
    miscellaneous: [
      {
        relationship: "Friends with",
        name: "Ernest Holt"
      },
      {
        relationship: "Girlfriend of",
        name: "Devon Wilson"
      },
      {
        relationship: "Instructed by",
        name: "Louis Grunewald"
      },
    ],
    pointAllotment: {
      skillPoints: 280,
      bonusSkillPoints: 150
    },
    money: 700,
  },
  Wilson: {
    name: "Devon Wilson",
    occupation: "US Navy - Lieutenant",
    sex: "M",
    age: 28,
    nationality: "USA",
    residence: "Norfolk",
    stats: {
      str: 13,
      dex: 11,
      int: 13,
      idea: 65,
      con: 12,
      app: 10,
      pow: 17,
      luck: 85,
      siz: 14,
      san: 50,
      edu: 17,
      know: 85,
      schools: "Miskatonic",
      degrees: "None",
      damageModifier: () => rollDice(1, 4),
      magicPoints: 17,
      hitPoints: 13,
      sanityPoints: 50
    },
    skills: {
      accounting: 10,
      anthropology: 0,
      archaeology: 0,
      astronomy: 0,
      bargain: 5,
      botany: 0,
      camouflage: 25,
      chemistry: 0,
      climb: 40,
      creditRating: 15,
      cryptography: 0,
      cthulhuMythos: 0,
      debate: 10,
      diagnoseDisease: 5,
      dodge: 22,
      driveAutomobile: 20,
      egyptology: 0,
      fastTalk: 5,
      firstAid: 30,
      geology: 0,
      hide: 10,
      antiquity: 20,
      jump: 25,
      law: 5,
      libraryUse: 25,
      linguist: 0,
      listen: 25,
      makeMaps: 10,
      mechanicalRepair: 20,
      navigate: 0,
      occult: 5,
      operateHeavyMachinery: 0,
      oratory: 5,
      pharmacy: 0,
      photography: 10,
      pickPocket: 5,
      pilotAircraft: 0,
      psychoanalysis: 0,
      psychology: 5,
      languageEnglish: 85,
      languageGerman: 0,
      languageLatin: 0,
      languageNordic: 0,
      languageEgHieroglyph: 0,
      ride: 5,
      sneak: 10,
      speak: 0,
      spotHidden: 25,
      survival: 5,
      swim: 25,
      throwAction: 25,
      track: 10,
      treatDisease: 5,
      treatPoison: 5
    },
    bonusSkills: {
      accounting: false,
      anthropology: false,
      archaeology: false,
      astronomy: false,
      bargain: false,
      botany: false,
      camouflage: false,
      chemistry: false,
      climb: false,
      creditRating: false,
      cryptography: true,
      cthulhuMythos: false,
      debate: false,
      diagnoseDisease: false,
      dodge: false,
      driveAutomobile: false,
      egyptology: false,
      fastTalk: false,
      firstAid: false,
      geology: false,
      hide: false,
      antiquity: false,
      jump: false,
      law: false,
      libraryUse: false,
      linguist: false,
      listen: false,
      makeMaps: true,
      mechanicalRepair: true,
      navigate: true,
      occult: false,
      operateHeavyMachinery: false,
      oratory: false,
      pharmacy: false,
      photography: false,
      pickPocket: false,
      pilotAircraft: false,
      psychoanalysis: false,
      psychology: false,
      languageEnglish: false,
      languageGerman: true,
      languageLatin: false,
      languageNordic: false,
      languageEgHieroglyph: false,
      ride: false,
      sneak: false,
      speak: false,
      spotHidden: false,
      survival: true,
      swim: true,
      throwAction: false,
      track: false,
      treatDisease: false,
      treatPoison: false
    },
    weapons: {
      fist: () => rollDice(1, 3) + rollDice(1, 4),
      kick: () => rollDice(1, 6) + rollDice(1, 4),
      headButt: () => rollDice(2, 4),
      grapple: 0,
      revolver45: () => rollDice(1, 10) + 2,
      rifle3006: () => rollDice(2, 6) + 3,
      gauge12: () => rollDice(2, 6)
    },
    miscellaneous: [
      {
        relationship: "Decorated by",
        name: "Ernest Holt"
      },
      {
        relationship: "Boyfriend of",
        name: "Nora McShane"
      },
      {
        relationship: "Instructed by",
        name: "Louis Grunewald"
      },
    ],
    pointAllotment: {
      skillPoints: 320,
      bonusSkillPoints: 150
    },
    money: 2500,
  },
};